INSERT INTO stocks (symbol, company_name, current_price, market) VALUES
('AAPL', 'Apple Inc.', 172.88, 'NASDAQ'),
('GOOGL', 'Alphabet Inc.', 134.50, 'NASDAQ'),
('AMZN', 'Amazon.com Inc.', 122.34, 'NASDAQ'),
('MSFT', 'Microsoft Corporation', 311.45, 'NASDAQ'),
('TSLA', 'Tesla Inc.', 239.58, 'NASDAQ'),
('NFLX', 'Netflix Inc.', 389.67, 'NASDAQ'),
('NVDA', 'NVIDIA Corporation', 452.25, 'NASDAQ'),
('META', 'Meta Platforms Inc.', 281.79, 'NASDAQ'),
('ORCL', 'Oracle Corporation', 89.45, 'NYSE'),
('DIS', 'Walt Disney Co.', 94.88, 'NYSE'),
('INTC', 'Intel Corporation', 34.67, 'NASDAQ'),
('CSCO', 'Cisco Systems Inc.', 48.23, 'NASDAQ'),
('IBM', 'International Business Machines', 138.89, 'NYSE'),
('PEP', 'PepsiCo Inc.', 176.43, 'NASDAQ'),
('KO', 'Coca-Cola Company', 61.25, 'NYSE'),
('WMT', 'Walmart Inc.', 151.02, 'NYSE'),
('JNJ', 'Johnson & Johnson', 163.42, 'NYSE'),
('BA', 'Boeing Co.', 187.26, 'NYSE'),
('PFE', 'Pfizer Inc.', 36.89, 'NYSE'),
('UBER', 'Uber Technologies Inc.', 51.14, 'NYSE');
